### ISSUE TITLE
uint dependency

### ISSUE THREAD

**Issue by Freyr666** [issuu/ocaml-zmq#43] opened 2017-08-10 07:13 UTC
It seems that zmq relies on uint, however uint is not presented in `depends`.

However even with uint installed I'm getting an error during zmq compilation:

```
#=== ERROR while compiling zmq.4.0-8 ==========================================#
# command      ocaml setup.ml -build
# path         /home/freyr/.opam/main/.opam-switch/build/zmq.4.0-8
# exit-code    1
# env-file     /home/freyr/.opam/log/zmq-19148-d2d111.env
# output-file  /home/freyr/.opam/log/zmq-19148-d2d111.out
### output ###
# [...]
# File "_tags", line 125, characters 44-84:
# Warning: the tag "oasis_executable_threadedloopback_native" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
# File "_tags", line 126, characters 23-63:
# Warning: the tag "oasis_executable_threadedloopback_native" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
# /home/freyr/.opam/main/bin/ocamlfind ocamlc -g -ccopt -I/usr/local/include -ccopt -I. -ccopt -I -ccopt /home/freyr/.opam/main/lib/stdint -ccopt -Wall -ccopt -Wextra -ccopt -O2 -c src/caml_zmq_stubs.c
# + /home/freyr/.opam/main/bin/ocamlfind ocamlc -g -ccopt -I/usr/local/include -ccopt -I. -ccopt -I -ccopt /home/freyr/.opam/main/lib/stdint -ccopt -Wall -ccopt -Wextra -ccopt -O2 -c src/caml_zmq_stubs.c
# src/caml_zmq_stubs.c:37:10: fatal error: uint64.h: No such file or directory
#  #include <uint64.h>
#           ^~~~~~~~~~
# compilation terminated.
# Command exited with code 2.
# E: Failure("Command ''/home/freyr/.opam/main/bin/ocamlbuild' src/libZMQ_stubs.a src/dllZMQ_stubs.so src/ZMQ.cma src/ZMQ.cmxa src/ZMQ.a src/ZMQ.cmxs examples/hwserver.native examples/hwclient.native examples/wuserver.native examples/wuclient.native examples/wuproxy.native examples/taskvent.native examples/taskwork.native examples/tasksink.native -tag debug' terminated with error code 10")
```

what's wrong?

It seems that oasis should use ~/.opam/main/include/ocaml_stdint include path instead of ~/.opam/main/lib/stdint. Any idea how to fix that?

**Comment by Freyr666** [comment] 2017-08-10 07:47
It seems that oasis should use `~/.opam/main/include/ocaml_stdint` include path instead of `~/.opam/main/lib/stdint`. Any idea how to fix that?

**Comment by kkirstein** [comment] 2017-08-10 15:22
I just stepped into the same error. It is caused by the stdint package, which changed the location of its header files to .opam/<switch>/include/ocaml_stdint, as described above. So, the first fix is to downgrade stdint to 3.0.0-0 (worked for me). Unfortunately, I have no experience with oasis to give some advice here (there is a $pkg_stdint var in the oasis setup, I have no clue how that is resolved).

**Comment by kkirstein** [comment] 2017-08-10 15:25
sorry, I meant downgrade to stdint **0.3.0-0**

**Comment by orbifx** [comment] 2017-08-15 11:24
I get a similar error. Is it the same problem?

```
# + /home/x/.opam/4.03.0/bin/ocamlfind ocamlc -g -ccopt -I/usr/local/include -ccopt -I. -ccopt -I -ccopt /home/x/.opam/4.03.0/lib/stdint -ccopt -Wall -ccopt -Wextra -ccopt -O2 -c src/caml_zmq_stubs.c
# In file included from src/caml_zmq_stubs.c:31:0:
# /usr/include/zmq_utils.h:44:9: note: #pragma message: Warning: zmq_utils.h is deprecated. All its functionality is provided by zmq.h.
#  #pragma message("Warning: zmq_utils.h is deprecated. All its functionality is provided by zmq.h.")
#          ^~~~~~~
# src/caml_zmq_stubs.c:37:10: fatal error: uint64.h: No such file or directory
#  #include <uint64.h>
#           ^~~~~~~~~~
# compilation terminated.
# Command exited with code 2
```

**Comment by orbifx** [comment] 2017-08-15 11:38
Seems it's noted here: https://github.com/andrenth/ocaml-stdint/issues/19

**Comment by orbifx** [comment] 2017-08-15 11:48
@kkirstein how did you downgrade stdint? I got errors with directory not being empty after removal. I wiped my .opam and started again pinning stdint to 0.3.0 and I get 

```
#=== ERROR while installing stdint.0.3.0 ======================================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -configure --prefix /home/x/.opam/system
# path         /home/x/.opam/system/build/stdint.0.3.0
# compiler     system (4.05.0)
# exit-code    2
# env-file     /home/x/.opam/system/build/stdint.0.3.0/stdint-24698-7afd23.env
# stdout-file  /home/x/.opam/system/build/stdint.0.3.0/stdint-24698-7afd23.out
# stderr-file  /home/x/.opam/system/build/stdint.0.3.0/stdint-24698-7afd23.err
### stderr ###
# Cannot find file ./setup.ml.
```

**Comment by kkirstein** [comment] 2017-08-15 12:28
Usually opam takes care of updating the respective package, when calling `opam pin add stdint 0.3.0-0`. Did you try a manual `opam update stdint && opam upgrade stdint`?
You could also deinstall stdint first, e.g. `opam remove stdint` and then check, remove the build directory manually, if there are still some residues (.opam/system/build/stdint.0.3.0).

BTW, on my system(s) (Ubuntu & cygwin), the available version of stdint is named 0.3.0-0

In case your opam setup is out-of-sync, there are some tipps here: [FAQ](https://opam.ocaml.org/doc/FAQ.html#IinstalledapackagebyhandusedocamlfindremovefiddledwiththeinstalledpackagesandOPAMisoutofsyncHelp)

**Comment by akabe** [comment] 2017-08-16 02:14
This problem was solved by @andrenth https://github.com/andrenth/ocaml-stdint/issues/19#issuecomment-322543648 in stdint 0.4.2. The new version will be released soon in opam-repository: https://github.com/ocaml/opam-repository/pull/10093.

@issuu Could you add constraint `stdint {>= '0.4.2'}` to opam files for all versions of zmq in opam-repository (after the release of stdint 0.4.2)?

**Comment by kkirstein** [comment] 2017-08-17 09:19
Just checked `zmq.4.0-8` with `stdint.0.4.2`: Compiles out-of-box now on Ubuntu 16.04 (I will also test on Windows cygwin/mingw64 during the next days, it usually takes 1..2 days for new releases to be available at opam-repository-mingw).

A side note: ocaml-zmq also works on Bash-for-Windows after updating Win10 to release 1703 (creators update)

**Comment by andersfugmann** [comment] 2018-03-07 06:56
@akabe Is it still relevant to add the constraint `stdint {>= '0.4.2'}` to opam file?

**Comment by akabe** [comment] 2018-03-07 07:30
Can ocaml-zmq be compiled with stdint 0.4.1 or below?

**Comment by kkirstein** [comment] 2018-03-07 08:52
As far as I remember, (automatic) installation failed only for stdint 0.4.0 & 0.4.1 (Could be fixed by manually copying the required header files). So, to be on the save side a constraint stdint <0.4.0 & >= 0.4.2 should be kept.
BTW, I never finished my last post: ocaml-zmq works with stdint 0.4.2 on Windows-Cygwin/mingw (and still does with stdint 0.5.1 today).

**Comment by akabe** [comment] 2018-03-07 09:14
@kkirstein Thanks. I keep the the constraint for stdint. However I think it should be added to opam file of ocaml-zmq because [ocaml-jupyter](https://akabe.github.io/ocaml-jupyter/) directly depends on ocaml-zmq, not on stdint. I remember that I added of the constraint to ocaml-jupyter for the time being.

I have no idea for installation of ocaml-zmq on Windows. I rarely use Windows and I have not installed OCaml on Windows ever.

**Comment by andersfugmann** [comment] 2018-03-07 09:37
See #50. The opam file should be used when pushing a new release to opam-repository.

**Comment by akabe** [comment] 2018-03-07 09:53
@andersfugmann Oh, the constraint is no longer required! I will remove it after the PR is merged. Thanks.

**Comment by andersfugmann** [comment] 2018-03-07 09:59
@akabe Not sure I follow. The library does not compiles with stdlib0.4.1 installed 
(complains about missing uint.h), hence the PR

**Comment by akabe** [comment] 2018-03-07 10:09
The opam file of ocaml-jupyter has the constraint `stdint >= 0.4.2` since ocaml-zmq (depended from ocaml-jupyter) cannot be built with `stdint < 0.4.1`, but ocaml-jupyter does not use stdint directly. I can remove the constraint from `ocaml-jupyter.opam` thanks to your PR.

**Comment by Leonidas-from-XIV** [comment] 2018-03-07 15:34
#50 was merged and will be part of the next release, therefore closing this.

**Closed by Leonidas-from-XIV** 2018-03-07 15:34 UTC
